name: Smartpreneur
favicon: null
layout_spectrum: 0.5504831946454942
typography_spectrum: 0.8658523762132972
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7341741961427033
  lightness: 0.5722598300781101
  saturation: 0.9356465900782496
  rhythmicContrast: 0.08053710544481874
purpose: []
