name: Smartpreneur
favicon: null
layout_spectrum: 0.75916
typography_spectrum: 0.8658523762132972
title: 'CONNECT | CREATE | INNOVATE'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e68f44'
    - '#a7a9ac'
    - '#dcddde'
    - '#ecac75'
  brandStrength: 0.7341741961427033
  lightness: 0.5722598300781101
  saturation: 0.9356465900782496
  rhythmicContrast: 0.08053710544481874
purpose: []
